// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SevenBySeven.Shared.Persistence;

#nullable disable

namespace SevenBySeven.Shared.Migrations
{
    [DbContext(typeof(SevenBySevenDbContext))]
    partial class SevenBySevenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SevenBySeven.Modules.Catalogue.Domain.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("artist_name");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<string>("CatalogueNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("catalogue_number");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<int?>("DiscogsMasterId")
                        .HasColumnType("integer")
                        .HasColumnName("discogs_master_id");

                    b.Property<int>("DiscogsReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("discogs_release_id");

                    b.Property<string>("FormatDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("format_description");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<string>("LabelName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label_name");

                    b.PrimitiveCollection<List<string>>("Styles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("styles");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_releases");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_releases_barcode");

                    b.HasIndex("CatalogueNumber")
                        .HasDatabaseName("ix_releases_catalogue_number");

                    b.HasIndex("DiscogsReleaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_discogs_release_id");

                    b.ToTable("releases", "catalogue");
                });

            modelBuilder.Entity("SevenBySeven.Modules.Catalogue.Domain.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Bpm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("bpm");

                    b.Property<string>("BpmSource")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bpm_source");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("position");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("Bpm")
                        .HasDatabaseName("ix_tracks_bpm");

                    b.HasIndex("ReleaseId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_release_id_position");

                    b.ToTable("tracks", "catalogue");
                });

            modelBuilder.Entity("SevenBySeven.Modules.Collection.Domain.Copy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_on");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("MediaCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_condition");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PricePaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_paid");

                    b.Property<string>("PricePaidCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("price_paid_currency")
                        .IsFixedLength();

                    b.Property<string>("PurchasedFrom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purchased_from");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("SleeveCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sleeve_condition");

                    b.HasKey("Id")
                        .HasName("pk_copies");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_copies_release_id");

                    b.ToTable("copies", "collection");
                });

            modelBuilder.Entity("SevenBySeven.Modules.Catalogue.Domain.Release", b =>
                {
                    b.OwnsOne("SevenBySeven.Modules.Catalogue.Domain.ReleaseDate", "Released", b1 =>
                        {
                            b1.Property<Guid>("ReleaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("released_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("released_month");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("released_year");

                            b1.HasKey("ReleaseId");

                            b1.ToTable("releases", "catalogue");

                            b1.WithOwner()
                                .HasForeignKey("ReleaseId")
                                .HasConstraintName("fk_releases_releases_id");
                        });

                    b.Navigation("Released");
                });

            modelBuilder.Entity("SevenBySeven.Modules.Catalogue.Domain.Track", b =>
                {
                    b.HasOne("SevenBySeven.Modules.Catalogue.Domain.Release", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracks_releases_release_id");
                });

            modelBuilder.Entity("SevenBySeven.Modules.Collection.Domain.Copy", b =>
                {
                    b.HasOne("SevenBySeven.Modules.Catalogue.Domain.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_copies_releases_release_id");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("SevenBySeven.Modules.Catalogue.Domain.Release", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
